import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeInitializer from "@/components/theme&effects/ThemeInitializer";
import MouseShadow from "@/components/theme&effects/MouseShadow";
import Navigation from "@/components/Navigation";
import { Ubuntu_Mono } from "next/font/google";
import Footer from "@/components/Footer";
//fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const ubuntuMono = Ubuntu_Mono({
    weight: ["400", "700"], // Regular and Bold (or add others as needed)
    subsets: ["latin"],
    variable: "--font-ubuntu-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ubuntuMono.variable} antialiased dark:bg-black bg-white`}
      >
      <ThemeInitializer/>
      <MouseShadow/>
        <div className={"flex flex-col justify-center items-center border"}>
            <Navigation/>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
